import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";
import GoogleCaptchaWrapper from "./components/GoogleCaptchaWrapper";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  >
        <NavBar />
            <GoogleCaptchaWrapper>
              {children} 
            </GoogleCaptchaWrapper>
            
         {/* <Footer /> */}
      </body>
     
    </html>
  );
}
